---
title: "assignmentXX"
format: html
author:
  name: Solai Le Fay
  affiliation:
    name: Boise State University
---

# Your first Quarto Document

For today's in-class work, you'll learn a few of the features of Quarto and get to practice using version control to track your changes to this document.

## Add some more details to the Header

Modify the yaml header to include your name and affiliation. Save the document and commit the changes.

## Write some text

I am originally from [Ashland, Oregon]{style="color:blue;"}. My thesis research *assesses the impact of various environmental factors such as weather, vegetation, and neighbor density on Burrowing Owl nest productivity and adult survival.*

Save the document and commit your change

## Write some code

Insert a code chunk and have R calculate the sum of the month, day, and year you were born.

Save the document and commit your change.

## Render the document

Assuming everything worked correctly you should now have a file named `inclass02.html`

Commit both the final `.qmd` file and the `.html` file together.

## Push your changes
